### ISSUE TITLE
lift Python 3.9 upper bound

### ISSUE THREAD

**Issue by bcdarwin** [jcreinhold/pymedio#15]
This is quite a restrictive upper bound -- tests pass fine on 3.10 and 3.11 (I didn't check the torchio tests).

**Comment by jcreinhold** [comment]
Yeah, I just haven't had the time to update this or my other packages. At some point I'd like to get around to raising this upper bound. A PR is definitely welcome.

**Comment by jcreinhold** [comment]
Fixed with 651bfe4df836de8a7fdd22e7f3e4d247a829ecf0

**Comment by jcreinhold** [comment]
v0.2.14 allows Python >=3.9
